export const GAME_ACTIONS = {
    PLAY_CARD: "PLAY_CARD",
    END_DEPLOY: "END_DEPLOY",
    START_PLAYER_TURN: "START_PLAYER_TURN",
    PLAYER_ATTACK: "PLAYER_ATTACK",
    END_PLAYER_TURN: "END_PLAYER_TURN",
    ENEMY_TURN: "ENEMY_TURN",
    CHECK_BATTLE_END: "CHECK_BATTLE_END"
};
