export const EFFECT_TYPES = {
    ATTACK_ANIMATION: "ATTACK_ANIMATION",
    DAMAGE_POP: "DAMAGE_POP",
    DEATH_ANIMATION: "DEATH_ANIMATION",
    WAIT: "WAIT",
    SNAPSHOT_RELEASE: "SNAPSHOT_RELEASE"
};
