export const GAME_PHASES = {
    SETUP: "SETUP",
    DEPLOY_PLAYER: "DEPLOY_PLAYER",
    BATTLE_PLAYER: "BATTLE_PLAYER",
    BATTLE_ENEMY: "BATTLE_ENEMY",
    BATTLE_RESULT: "BATTLE_RESULT",
    GAME_END: "GAME_END"
};
